# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YFHtpHEY8ErrD8NxQlwaT7_FQsLCJfnd
"""

import pandas as pd
baza={
    "FISH": ["Matkarimov Zohidbek", "Kamilova Dilnura","Qosimjonov Sherzodbek","Qosimjonova Shahlo","Allaberganov Suhrob","Abduvaliyev Donyorbek","Ikromov Islomjon","Mansurov Avazbek","Baxtiyorova Tabassum","Baxtiyorov Ezozbek" ] ,
    "Yoshi":["14","17","21","14","19","19","19","19","18","16"],
    "Jinsi":["o'g'il bola","qiz bola","o'g'il bola","qiz bola","o'g'il bola","o'g'il bola","o'g'il bola","o'g'il bola","qiz bola","o'g'il bola"],
    "Qaysi maktabda o'qishi":["21-maktab","20-maktab","28-maktab","54-maktab","578-maktab","01-maktab","73-maktab","32-maktab","45-maktab","12-maktab"],
    "Manzili":["xorazm shahar","xiva shahar","margilon","fargona","jizzax","buxoro","samarqand","termiz","toshkent","navoiy"],
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['Jinsi']=="qiz bola"]
print(filtr)

Izlash=filtr[filtr['Manzili']=="toshkent"]
print(Izlash)